apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-flask-chart
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flask-chart
  template:
    metadata:
      labels:
        app: flask-chart
    spec:
      containers:
      - name: flask-chart
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
